### ISSUE TITLE
Show notification when station or track changes

### ISSUE THREAD

**Issue by dsandstrom** [DreamDevel/eRadio#6]
Manjaro - Pantheon - eRadio v1.2

Maybe it's a limitation of not using elemantary OS, but I only see a notification when I first start a station.

**Comment by geocool** [comment]
Notifications are being displayed when eradio doesn't have focus (e.g. minimized). 
If not, the problem may occur because you are not using elementary OS.
Please note that we don't support distributions other than elementary OS currently.

Also as mentioned in README : 
> Project is under development. Please report bugs or create pull requests after the version 2.0 is > released. 

Thanks for taking the time to report your problem.

**Comment by dsandstrom** [comment]
Thanks for the response and awesome radio player.  Sorry I missed the note about not reporting until v2.0.
